# Generated by Django 3.2.16 on 2023-01-17 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LtiProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('platform_id', models.URLField(help_text='Platform ID this profile belongs to.', max_length=255, verbose_name='Platform ID')),
                ('client_id', models.CharField(help_text='Client ID generated by the LTI platform.', max_length=255, verbose_name='Client ID')),
                ('subject_id', models.CharField(help_text='Identifies the entity that initiated the launch request.', max_length=255, verbose_name='Subject ID')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='openedx_lti_tool_plugin_lti_profile', to=settings.AUTH_USER_MODEL, verbose_name='Open edX user')),
            ],
            options={
                'verbose_name': 'LTI Profile',
                'verbose_name_plural': 'LTI Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='ltiprofile',
            index=models.Index(fields=['platform_id', 'client_id', 'subject_id'], name='lti_profile_identity_claims'),
        ),
        migrations.AlterUniqueTogether(
            name='ltiprofile',
            unique_together={('platform_id', 'client_id', 'subject_id')},
        ),
    ]
