# Generated by Django 3.2.16 on 2023-07-28 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool_config', '0001_initial'),
        ('openedx_lti_tool_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CourseAccessConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_course_ids', models.TextField(default=[], help_text='List of allowed courses IDs. Example: ["id-1", "id-2", ...]', verbose_name='Allowed Course IDs')),
                ('lti_tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='openedx_lti_tool_plugin_course_permission', to='lti1p3_tool_config.ltitool', verbose_name='LTI Tool')),
            ],
            options={
                'verbose_name': 'Course access configuration',
                'verbose_name_plural': 'Course access configurations',
            },
        ),
    ]
