# Generated by Django 3.2.17 on 2023-08-11 01:11

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_lti_tool_plugin', '0002_add_course_access_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtiGradedResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_key', opaque_keys.edx.django.models.LearningContextKeyField(help_text='The opaque key string of the resource.', max_length=255)),
                ('lineitem', models.URLField(help_text='The AGS lineitem URL.', max_length=255)),
                ('lti_profile', models.ForeignKey(help_text='The LTI profile that launched the resource.', on_delete=django.db.models.deletion.CASCADE, related_name='openedx_lti_tool_plugin_graded_resource', to='openedx_lti_tool_plugin.ltiprofile')),
            ],
            options={
                'verbose_name': 'LTI graded resource',
                'verbose_name_plural': 'LTI graded resources',
                'unique_together': {('lti_profile', 'context_key', 'lineitem')},
            },
        ),
    ]
