# Generated by Django 3.2.17 on 2023-09-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_lti_tool_plugin', '0003_add_lti_graded_resource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ltiprofile',
            options={'verbose_name': 'LTI profile', 'verbose_name_plural': 'LTI profiles'},
        ),
        migrations.AddField(
            model_name='ltiprofile',
            name='pii',
            field=models.JSONField(default=dict, help_text='Profile PII.', verbose_name='PII'),
        ),
    ]
