# Generated by Django 3.2.17 on 2023-10-04 17:56

from django.db import migrations, models
import openedx_lti_tool_plugin.models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_lti_tool_plugin', '0004_add_profile_pii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltigradedresource',
            name='context_key',
            field=models.CharField(help_text='The opaque key string of the resource.', max_length=255, validators=[openedx_lti_tool_plugin.models.validate_context_key]),
        ),
    ]
