# Generated by Django 3.2.17 on 2025-04-04 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0016_through_model_for_user_partition_groups_2'),
        ('lti1p3_tool_config', '0001_initial'),
        ('openedx_lti_tool_plugin', '0005_alter_ltigradedresource_context_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseAccessConfiguration',
            new_name='LtiToolConfiguration',
        ),
        migrations.AlterField(
            model_name='ltitoolconfiguration',
            name='lti_tool',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='openedx_lti_tool_plugin_configuration',
                to='lti1p3_tool_config.ltitool',
                verbose_name='LTI Tool'
            ),
        ),
        migrations.AddField(
            model_name='ltitoolconfiguration',
            name='user_provisioning_mode',
            field=models.CharField(
                choices=[
                    ('new_only', 'New accounts only (automatic)'),
                    ('existing_and_new', 'Existing and new accounts (prompt)'),
                    ('existing_only', 'Existing accounts only (prompt)')
                ],
                default='new_only',
                help_text='Determines how user accounts are provisioned during LTI authentication.',
                max_length=50,
                verbose_name='User Provisioning Mode'
            ),
        ),
        migrations.AlterModelOptions(
            name='ltitoolconfiguration',
            options={
                'verbose_name': 'LTI tool configuration',
                'verbose_name_plural': 'LTI tool configurations'
            },
        ),
    ]
