# Generated by Django 3.2.17 on 2024-07-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0016_through_model_for_user_partition_groups_2'),
        ('openedx_lti_tool_plugin', '0005_alter_ltigradedresource_context_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContext',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('learning_sequences.coursecontext',),
        ),
    ]
