# Generated by Django 3.2.17 on 2025-04-11 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool_config', '0001_initial'),
        ('openedx_lti_tool_plugin', '0006_rename_course_access_configuration_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltitoolconfiguration',
            name='lti_tool',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='openedx_lti_tool_plugin_lti_tool_configuration', to='lti1p3_tool_config.ltitool', verbose_name='LTI Tool'),
        ),
        migrations.AlterField(
            model_name='ltitoolconfiguration',
            name='user_provisioning_mode',
            field=models.CharField(choices=[('new_only', 'New accounts only (automatic)'), ('existing_and_new', 'Existing and new accounts (prompt)'), ('existing_only', 'Existing accounts only (prompt)')], default='new_only', help_text='\n        <p>Determines how user accounts are provisioned during an LTI launch:</p>\n        <ul>\n          <li><strong>New accounts only (automatic)</strong> -\n            New accounts are created automatically on first launch\n            and reused for subsequent launches.</li>\n          <li><strong>Existing and new accounts (prompt)</strong> -\n            User prompted to link an existing account or create a new one.\n            That selection is used for subsequent launches.</li>\n          <li><strong>Existing accounts only (prompt)</strong> -\n            Only existing accounts may be used. Without an existing account,\n            users cannot access shared resources.</li>\n        </ul>\n        ', max_length=50, verbose_name='User Provisioning Mode'),
        ),
    ]
