# Generated by Django 3.2.17 on 2025-04-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0016_through_model_for_user_partition_groups_2'),
        ('openedx_lti_tool_plugin', '0007_update_lti_tool_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContext',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('learning_sequences.coursecontext',),
        ),
    ]
