# Generated by Django 3.2.17 on 2025-04-11 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openedx_lti_tool_plugin', '0008_add_course_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiprofile',
            name='pii',
            field=models.JSONField(default=dict, help_text='Personally Identifiable Information.', verbose_name='PII'),
        ),
        migrations.AlterField(
            model_name='ltiprofile',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='openedx_lti_tool_plugin_lti_profile', to=settings.AUTH_USER_MODEL, verbose_name='Open edX user'),
        ),
        migrations.AlterField(
            model_name='ltiprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
